using CodeCarver.Core.Frontend;
using Xunit;

namespace CodeCarver.Tests.Frontend;

/// <summary>
/// Tests the build-log scraper against real captured compiler command lines (Lua, cJSON, tiny-AES-c,
/// generated by `make -n` with the pinned toolchain) plus synthetic edge cases. These real lines are
/// the honest input the config provider must handle when a build log — not a compile_commands.json —
/// is all we have.
/// </summary>
public class BuildLogScraperTests
{
    [Fact]
    public void RealLua_ExtractsDefineAndStd()
    {
        const string line = "gcc -Wall -O2 -Wextra -Wshadow -std=c99 -DLUA_USE_LINUX -fno-common -c -o lapi.o lapi.c";
        var cmds = BuildLogScraper.Parse(line);

        var cmd = Assert.Single(cmds);
        Assert.Equal("lapi.c", cmd.File);
        Assert.Contains("LUA_USE_LINUX", cmd.Defines);
    }

    [Fact]
    public void RealCJson_ExtractsIncludeAndSource()
    {
        const string line = "gcc -std=c89 -fPIC -pedantic -Wall -Werror -fstack-protector cJSON.c test.c -o cJSON_test -lm -I.";
        var cmds = BuildLogScraper.Parse(line);

        // Two source files on one line -> two commands, sharing flags.
        Assert.Equal(2, cmds.Count);
        Assert.Contains(cmds, c => c.File == "cJSON.c");
        Assert.Contains(cmds, c => c.File == "test.c");
        Assert.All(cmds, c => Assert.Contains(".", c.Includes));
    }

    [Fact]
    public void RealTinyAes_SimpleCompile()
    {
        const string line = "gcc -Wall -Os -c -o aes.o aes.c";
        var cmd = Assert.Single(BuildLogScraper.Parse(line));
        Assert.Equal("aes.c", cmd.File);
    }

    [Fact]
    public void Synthetic_DefinesAndIncludes_BothSpacedAndAttached()
    {
        const string line = "cc -DFOO=1 -DBAR -I include -Isrc/inc -c foo.c";
        var cmd = Assert.Single(BuildLogScraper.Parse(line));

        Assert.Equal("foo.c", cmd.File);
        Assert.Equal(new[] { "FOO=1", "BAR" }, cmd.Defines);
        Assert.Equal(new[] { "include", "src/inc" }, cmd.Includes);
    }

    [Fact]
    public void LinkOnlyLine_IsSkipped()
    {
        const string line = "gcc -o app main.o util.o -lm";
        Assert.Empty(BuildLogScraper.Parse(line));
    }

    [Fact]
    public void CrossCompiler_AndLeadingCd_AreHandled()
    {
        const string line = "cd build/core && /opt/gcc-arm/bin/arm-none-eabi-gcc -DSTM32 -Iinc -c startup.c";
        var cmd = Assert.Single(BuildLogScraper.Parse(line));

        Assert.Equal("startup.c", cmd.File);
        Assert.Equal("build/core", cmd.Directory);
        Assert.Contains("STM32", cmd.Defines);
        Assert.Contains("inc", cmd.Includes);
    }

    [Fact]
    public void MsvcStyleFlags_AreHandled()
    {
        const string line = "cl.exe /c /DWIN32 /DDEBUG=1 /Iinclude foo.cpp";
        var cmd = Assert.Single(BuildLogScraper.Parse(line));

        Assert.Equal("foo.cpp", cmd.File);
        Assert.Equal(new[] { "WIN32", "DEBUG=1" }, cmd.Defines);
        Assert.Contains("include", cmd.Includes);
    }

    [Fact]
    public void QuotedIncludePathWithSpaces_IsOneToken()
    {
        const string line = "gcc -I\"C:/Program Files/sdk/inc\" -c a.c";
        var cmd = Assert.Single(BuildLogScraper.Parse(line));
        Assert.Contains("C:/Program Files/sdk/inc", cmd.Includes);
    }

    [Fact]
    public void IncludeSearchVariants_isystem_iquote_idirafter_AreCaptured()
    {
        // Embedded builds pass toolchain/CMSIS/HAL headers via -isystem etc., not just -I. All feed include
        // resolution (a non-sibling .inc reached this way otherwise only surfaces via the basename fallback).
        const string line = "arm-none-eabi-gcc -Icore -isystem /opt/cmsis/inc -iquote local -idirafter after -c m.c";
        var cmd = Assert.Single(BuildLogScraper.Parse(line));
        Assert.Equal(new[] { "core", "/opt/cmsis/inc", "local", "after" }, cmd.Includes);
    }

    [Fact]
    public void SiblingToolchainTools_AreNotTreatedAsCompiles()
    {
        // clang-tidy carries a .c token but is NOT a compile; gcc-ar / arm-none-eabi-ld share a prefix but
        // aren't compilers. None should produce a compile command.
        Assert.Empty(BuildLogScraper.Parse("clang-tidy foo.c -- -Iinc"));
        Assert.Empty(BuildLogScraper.Parse("gcc-ar rcs libx.a a.o b.o"));
        Assert.Empty(BuildLogScraper.Parse("arm-none-eabi-ld -T link.ld a.o -o out.elf"));
    }

    [Fact]
    public void QuotedDefineValue_KeepsSpacesAsOneDefine()
    {
        const string line = "gcc -D\"MSG=hello world\" -c a.c";
        var cmd = Assert.Single(BuildLogScraper.Parse(line));
        Assert.Contains("MSG=hello world", cmd.Defines);
    }

    [Fact]
    public void ResponseFileArg_DoesNotCrash_StillFindsInlineSource()
    {
        // @rsp files aren't expanded (a documented limitation) but must never crash; a visible source still
        // yields a command (its .rsp-only flags are simply unseen).
        var cmd = Assert.Single(BuildLogScraper.Parse("gcc @flags.rsp -DINLINE -c a.c"));
        Assert.Equal("a.c", cmd.File);
        Assert.Contains("INLINE", cmd.Defines);
    }

    [Fact]
    public void MultiLineLog_ParsesEachCompileLine()
    {
        const string log = """
            gcc -DA -c a.c
            echo building...
            gcc -DB -c b.c
            ar rcs libx.a a.o b.o
            """;
        var cmds = BuildLogScraper.Parse(log);
        Assert.Equal(2, cmds.Count);
    }

    // --- compile_commands.json (CMake + the synthetic generator emit this; --build-log accepts it too) ---

    [Fact]
    public void CompileCommandsJson_GeneratorCommandForm_ExtractsIncludesAndFile()
    {
        // Mirrors make-firmware-corpus.ps1's emitted entry: clang -I"<dir>" -I"<out>" -c "<file>", with the
        // escaped inner quotes a real compile_commands.json carries. (Raw string => the \" are literal.)
        const string json = """
            [
              { "directory": "/proj/block0", "file": "/proj/block0/src_0.c",
                "command": "clang -I\"/proj/block0\" -I\"/proj\" -c \"/proj/block0/src_0.c\"" }
            ]
            """;
        var cmd = Assert.Single(BuildLogScraper.Parse(json));
        Assert.Equal("/proj/block0/src_0.c", cmd.File);
        Assert.Equal(new[] { "/proj/block0", "/proj" }, cmd.Includes);
    }

    [Fact]
    public void CompileCommandsJson_ArgumentsForm_ExtractsDefinesAndIncludes()
    {
        // The argv-array form (clang -MJ / some tools emit this instead of a command string).
        const string json = """
            [
              { "directory": "/p", "file": "/p/main.c",
                "arguments": ["arm-none-eabi-gcc", "-DSTM32F407xx", "-DUSE_HAL", "-I", "/p/inc",
                              "-isystem", "/opt/cmsis", "-c", "/p/main.c"] }
            ]
            """;
        var cmd = Assert.Single(BuildLogScraper.Parse(json));
        Assert.Equal("/p/main.c", cmd.File);
        Assert.Equal(new[] { "STM32F407xx", "USE_HAL" }, cmd.Defines);
        Assert.Equal(new[] { "/p/inc", "/opt/cmsis" }, cmd.Includes);
    }

    [Fact]
    public void CompileCommandsJson_MultipleEntries_OneCommandPerTU()
    {
        const string json = """
            [
              { "directory": "/p", "file": "/p/a.c", "command": "gcc -DA -Iinc -c /p/a.c" },
              { "directory": "/p", "file": "/p/b.c", "command": "gcc -DB -c /p/b.c" }
            ]
            """;
        var cmds = BuildLogScraper.Parse(json);
        Assert.Equal(2, cmds.Count);
        Assert.Contains(cmds, c => c.File == "/p/a.c" && c.Defines.Contains("A") && c.Includes.Contains("inc"));
        Assert.Contains(cmds, c => c.File == "/p/b.c" && c.Defines.Contains("B"));
    }

    [Fact]
    public void CompileCommandsJson_Malformed_ReturnsEmpty_NoThrow()
    {
        // A truncated/invalid DB must be tolerated (empty), exactly like an unrecognised log line — never fatal.
        var ex = Record.Exception(() => Assert.Empty(BuildLogScraper.Parse("[ { \"file\": \"a.c\", \"command\": ")));
        Assert.Null(ex);
    }

    [Fact]
    public void Undef_LastWins_OverDefine()
    {
        // The compiler applies -D/-U left-to-right; ignoring -U wrongly kept the #ifdef branch of a macro the
        // build explicitly undefined (eval-#9). Last occurrence wins.
        var undef = Assert.Single(BuildLogScraper.Parse("gcc -DFEATURE -UFEATURE -c a.c"));
        Assert.DoesNotContain(undef.Defines, d => d == "FEATURE" || d.StartsWith("FEATURE="));
        var redef = Assert.Single(BuildLogScraper.Parse("gcc -UX -DX=1 -c a.c"));
        Assert.Contains("X=1", redef.Defines);
        var attached = Assert.Single(BuildLogScraper.Parse("clang -DA -DB -UA -c a.c"));
        Assert.Equal(new[] { "B" }, attached.Defines);            // A defined then undefined -> only B
    }

    [Fact]
    public void BackslashEscapedQuote_InCommand_IsStrippedAndGroups()
    {
        // A shell/command-string form carries \"...\" escaping (compile_commands.json 'command', shell logs).
        // Escaped quotes group and strip like normal quotes: -DVER=\"1.0\" -> VER=1.0 (no stray \1.0\), and
        // -I\"inc dir\" -> one include dir "inc dir" (space grouped, no literal backslashes/quotes).
        var c = Assert.Single(BuildLogScraper.Parse("gcc -DVER=\\\"1.0\\\" -I\\\"inc dir\\\" -c a.c"));
        Assert.Contains("VER=1.0", c.Defines);
        Assert.Contains("inc dir", c.Includes);
    }

    [Fact]
    public void WindowsBackslashPaths_AreNotTreatedAsEscapes()
    {
        // A bare backslash (Windows separator) is NOT an escape — only \" / \' are — so C:\foo survives.
        var c = Assert.Single(BuildLogScraper.Parse("gcc -IC:\\proj\\inc -c a.c"));
        Assert.Contains(@"C:\proj\inc", c.Includes);
    }

    [Fact]
    public void StandaloneCdLine_SetsDirectoryForFollowingCommands()
    {
        // A `cd DIR` on its own line (not `cd DIR && gcc`) must set the working dir for later commands.
        const string log = "cd build/core\ngcc -DX -Iinc -c a.c\n";
        var c = Assert.Single(BuildLogScraper.Parse(log));
        Assert.Equal("build/core", c.Directory);
        Assert.Equal("a.c", c.File);
    }

    [Fact]
    public void MakeEnteringLeavingDirectory_TracksWorkingDir()
    {
        // GNU `make -w` brackets recursive sub-builds with Entering/Leaving directory lines — real logs use
        // these everywhere; a relative -I otherwise resolves against the wrong base (eval-#10).
        const string log = """
            make[1]: Entering directory '/proj/src'
            gcc -Iinc -c a.c
            make[1]: Leaving directory '/proj/src'
            gcc -c b.c
            """;
        var cmds = BuildLogScraper.Parse(log);
        Assert.Equal("/proj/src", cmds.Single(c => c.File == "a.c").Directory);
        Assert.Equal(".", cmds.Single(c => c.File == "b.c").Directory);   // back out after Leaving
    }

    [Fact]
    public void ManifestJsonObject_IsNotMisreadAsCompileDb()
    {
        // The generator's ground-truth manifest is a JSON OBJECT ({...}), NOT a compile DB ([...]). Feeding it
        // to --build-log by mistake must yield no bogus compile commands (only a leading '[' triggers JSON).
        const string json = """{ "_meta": { "manifestVersion": 1 }, "symbols": { "func_0": { "def": "src_0.c:10", "refs": [] } } }""";
        Assert.Empty(BuildLogScraper.Parse(json));
    }
}
