using CodeCarver.Core.Frontend;
using Xunit;

namespace CodeCarver.Tests.Frontend;

/// <summary>
/// Tests the build-log scraper against real captured compiler command lines (Lua, cJSON, tiny-AES-c,
/// generated by `make -n` with the pinned toolchain) plus synthetic edge cases. These real lines are
/// the honest input the config provider must handle when a build log — not a compile_commands.json —
/// is all we have.
/// </summary>
public class BuildLogScraperTests
{
    [Fact]
    public void RealLua_ExtractsDefineAndStd()
    {
        const string line = "gcc -Wall -O2 -Wextra -Wshadow -std=c99 -DLUA_USE_LINUX -fno-common -c -o lapi.o lapi.c";
        var cmds = BuildLogScraper.Parse(line);

        var cmd = Assert.Single(cmds);
        Assert.Equal("lapi.c", cmd.File);
        Assert.Contains("LUA_USE_LINUX", cmd.Defines);
    }

    [Fact]
    public void RealCJson_ExtractsIncludeAndSource()
    {
        const string line = "gcc -std=c89 -fPIC -pedantic -Wall -Werror -fstack-protector cJSON.c test.c -o cJSON_test -lm -I.";
        var cmds = BuildLogScraper.Parse(line);

        // Two source files on one line -> two commands, sharing flags.
        Assert.Equal(2, cmds.Count);
        Assert.Contains(cmds, c => c.File == "cJSON.c");
        Assert.Contains(cmds, c => c.File == "test.c");
        Assert.All(cmds, c => Assert.Contains(".", c.Includes));
    }

    [Fact]
    public void RealTinyAes_SimpleCompile()
    {
        const string line = "gcc -Wall -Os -c -o aes.o aes.c";
        var cmd = Assert.Single(BuildLogScraper.Parse(line));
        Assert.Equal("aes.c", cmd.File);
    }

    [Fact]
    public void Synthetic_DefinesAndIncludes_BothSpacedAndAttached()
    {
        const string line = "cc -DFOO=1 -DBAR -I include -Isrc/inc -c foo.c";
        var cmd = Assert.Single(BuildLogScraper.Parse(line));

        Assert.Equal("foo.c", cmd.File);
        Assert.Equal(new[] { "FOO=1", "BAR" }, cmd.Defines);
        Assert.Equal(new[] { "include", "src/inc" }, cmd.Includes);
    }

    [Fact]
    public void LinkOnlyLine_IsSkipped()
    {
        const string line = "gcc -o app main.o util.o -lm";
        Assert.Empty(BuildLogScraper.Parse(line));
    }

    [Fact]
    public void CrossCompiler_AndLeadingCd_AreHandled()
    {
        const string line = "cd build/core && /opt/gcc-arm/bin/arm-none-eabi-gcc -DSTM32 -Iinc -c startup.c";
        var cmd = Assert.Single(BuildLogScraper.Parse(line));

        Assert.Equal("startup.c", cmd.File);
        Assert.Equal("build/core", cmd.Directory);
        Assert.Contains("STM32", cmd.Defines);
        Assert.Contains("inc", cmd.Includes);
    }

    [Fact]
    public void MsvcStyleFlags_AreHandled()
    {
        const string line = "cl.exe /c /DWIN32 /DDEBUG=1 /Iinclude foo.cpp";
        var cmd = Assert.Single(BuildLogScraper.Parse(line));

        Assert.Equal("foo.cpp", cmd.File);
        Assert.Equal(new[] { "WIN32", "DEBUG=1" }, cmd.Defines);
        Assert.Contains("include", cmd.Includes);
    }

    [Fact]
    public void QuotedIncludePathWithSpaces_IsOneToken()
    {
        const string line = "gcc -I\"C:/Program Files/sdk/inc\" -c a.c";
        var cmd = Assert.Single(BuildLogScraper.Parse(line));
        Assert.Contains("C:/Program Files/sdk/inc", cmd.Includes);
    }

    [Fact]
    public void IncludeSearchVariants_isystem_iquote_idirafter_AreCaptured()
    {
        // Embedded builds pass toolchain/CMSIS/HAL headers via -isystem etc., not just -I. All feed include
        // resolution (a non-sibling .inc reached this way otherwise only surfaces via the basename fallback).
        const string line = "arm-none-eabi-gcc -Icore -isystem /opt/cmsis/inc -iquote local -idirafter after -c m.c";
        var cmd = Assert.Single(BuildLogScraper.Parse(line));
        Assert.Equal(new[] { "core", "/opt/cmsis/inc", "local", "after" }, cmd.Includes);
    }

    [Fact]
    public void SiblingToolchainTools_AreNotTreatedAsCompiles()
    {
        // clang-tidy carries a .c token but is NOT a compile; gcc-ar / arm-none-eabi-ld share a prefix but
        // aren't compilers. None should produce a compile command.
        Assert.Empty(BuildLogScraper.Parse("clang-tidy foo.c -- -Iinc"));
        Assert.Empty(BuildLogScraper.Parse("gcc-ar rcs libx.a a.o b.o"));
        Assert.Empty(BuildLogScraper.Parse("arm-none-eabi-ld -T link.ld a.o -o out.elf"));
    }

    [Fact]
    public void QuotedDefineValue_KeepsSpacesAsOneDefine()
    {
        const string line = "gcc -D\"MSG=hello world\" -c a.c";
        var cmd = Assert.Single(BuildLogScraper.Parse(line));
        Assert.Contains("MSG=hello world", cmd.Defines);
    }

    [Fact]
    public void ResponseFileArg_DoesNotCrash_StillFindsInlineSource()
    {
        // @rsp files aren't expanded (a documented limitation) but must never crash; a visible source still
        // yields a command (its .rsp-only flags are simply unseen).
        var cmd = Assert.Single(BuildLogScraper.Parse("gcc @flags.rsp -DINLINE -c a.c"));
        Assert.Equal("a.c", cmd.File);
        Assert.Contains("INLINE", cmd.Defines);
    }

    [Fact]
    public void MultiLineLog_ParsesEachCompileLine()
    {
        const string log = """
            gcc -DA -c a.c
            echo building...
            gcc -DB -c b.c
            ar rcs libx.a a.o b.o
            """;
        var cmds = BuildLogScraper.Parse(log);
        Assert.Equal(2, cmds.Count);
    }
}
