#ifndef ELDRITCH_H
#define ELDRITCH_H
int macros_demo(void);
int board_id(void);
int hook(void);
int ritual(void);
int chant(void);
int sigil(void);
int fast_copy(int a);
int cfg_demo(void);
int split_head(int x);
int split_head_alt(int x);
int knr_add();
int knr_apply();
int proto_mul(int a, int b);
int dispatch_demo(int i);
int paste_demo(void);
int xmacro_demo(void);
int unity_demo(void);
int ctor_demo(void);
int parens_demo(void);
int body_inc(int x);
int get_speed(void);
int digraph_fn(int a);
int generic_demo(void);
int cleanup_demo(void);
int inline_demo(void);
int exported_fn(void);
int comment_head(void);
int cont_head(void);
int variant_one(void);
int variant_two(void);
int cult_demo(void);
int chant2(void);
int (*pick(int k))(int);
int cl_demo(void);
int weakref_demo(void);
int field_demo(void);
int tricky_demo(void);
int pair_x(void);
int pair_x_rev(void);
int rename_demo(void);
int line_fn(void);
int line_fn2(void);
int café(void);
int if0_fn(void);
int hdr_demo(void);
#endif
